// data.js
export const countryData = {
  armenia: {
    cost: "$900",
    climate: "Умеренный",
    safety: "Средняя",
    healthcare: "Базовая",
    internet: "Хороший",
    nomadVisa: "Нет",
    banking: "Средний уровень",
  },
  serbia: {
    cost: "$800",
    climate: "Континентальный",
    safety: "Выше среднего",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Да",
    banking: "Развитая",
  },
  philippines: {
    cost: "$750",
    climate: "Тропический",
    safety: "Низкая",
    healthcare: "Слабая",
    internet: "Низкое качество",
    nomadVisa: "Нет",
    banking: "Ограниченная",
  },
  vietnam: {
    cost: "$700",
    climate: "Тропический",
    safety: "Средняя",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Пока нет",
    banking: "Средний",
  },
  albania: {
    cost: "$650",
    climate: "Средиземноморский",
    safety: "Хорошая",
    healthcare: "Средняя",
    internet: "Средний",
    nomadVisa: "Да",
    banking: "Развивающаяся",
  },
  georgia: {
    cost: "$600",
    climate: "Умеренно-континентальный",
    safety: "Средняя",
    healthcare: "Базовая",
    internet: "Хороший",
    nomadVisa: "Да",
    banking: "Развивающаяся",
  },
  mexico: {
    cost: "$900",
    climate: "Тропический/сухой",
    safety: "Средняя",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Да",
    banking: "Развитая",
  },
  portugal: {
    cost: "$1200",
    climate: "Средиземноморский",
    safety: "Высокая",
    healthcare: "Хорошая",
    internet: "Отличный",
    nomadVisa: "Да",
    banking: "Развитая",
  },
  thailand: {
    cost: "$800",
    climate: "Тропический",
    safety: "Средняя",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Пока нет",
    banking: "Средняя",
  },
  turkiye: {
    cost: "$700",
    climate: "Разнообразный",
    safety: "Средняя",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Нет",
    banking: "Средняя",
  },
};
