export const countryData = {
  armenia: {
    climate: "Континентальный",
    safety: "Средняя",
    healthcare: "Базовая",
    internet: "Хороший",
    nomadVisa: "Нет",
    banking: "Средний",
    russianCommunity: "Есть",
    visaRequired: "Нет",
  },
  serbia: {
    climate: "Континентальный",
    safety: "Средняя",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Да",
    banking: "Развитая",
    russianCommunity: "Есть",
    visaRequired: "Нет",
  },
  philippines: {
    climate: "Тропический",
    safety: "Низкая",
    healthcare: "Слабая",
    internet: "Низкое качество",
    nomadVisa: "Нет",
    banking: "Ограниченная",
    russianCommunity: "Нет",
    visaRequired: "Да",
  },
  vietnam: {
    climate: "Тропический",
    safety: "Средняя",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Пока нет",
    banking: "Средний",
    russianCommunity: "Нет",
    visaRequired: "Нет",
  },
  albania: {
    climate: "Средиземноморский",
    safety: "Хорошая",
    healthcare: "Средняя",
    internet: "Средний",
    nomadVisa: "Да",
    banking: "Развивающаяся",
    russianCommunity: "Есть",
    visaRequired: "Нет",
  },
  georgia: {
    climate: "Умеренно-континентальный",
    safety: "Средняя",
    healthcare: "Базовая",
    internet: "Хороший",
    nomadVisa: "Да",
    banking: "Развивающаяся",
    russianCommunity: "Есть",
    visaRequired: "Нет",
  },
  mexico: {
    climate: "Тропический/сухой",
    safety: "Средняя",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Да",
    banking: "Развитая",
    russianCommunity: "Нет",
    visaRequired: "Да",
  },
  portugal: {
    climate: "Средиземноморский",
    safety: "Высокая",
    healthcare: "Хорошая",
    internet: "Отличный",
    nomadVisa: "Да",
    banking: "Развитая",
    russianCommunity: "Нет",
    visaRequired: "Нет",
  },
  thailand: {
    climate: "Тропический",
    safety: "Средняя",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Пока нет",
    banking: "Средняя",
    russianCommunity: "Нет",
    visaRequired: "Да",
  },
  turkiye: {
    climate: "Разнообразный",
    safety: "Средняя",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Нет",
    banking: "Средняя",
    russianCommunity: "Есть",
    visaRequired: "Нет",
  },
};
