// data.js
export const countryData = {
  армения: {
    cost: "$900",
    climate: "Умеренный",
    safety: "Средняя",
    healthcare: "Базовая",
    internet: "Хороший",
    nomadVisa: "Нет",
    banking: "Средний уровень",
  },
  сербия: {
    cost: "$800",
    climate: "Континентальный",
    safety: "Выше среднего",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Да",
    banking: "Развитая",
  },
  филиппины: {
    cost: "$750",
    climate: "Тропический",
    safety: "Низкая",
    healthcare: "Слабая",
    internet: "Низкое качество",
    nomadVisa: "Нет",
    banking: "Ограниченная",
  },
  вьетнам: {
    cost: "$700",
    climate: "Тропический",
    safety: "Средняя",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Пока нет",
    banking: "Средний",
  },
  албания: {
    cost: "$650",
    climate: "Средиземноморский",
    safety: "Хорошая",
    healthcare: "Средняя",
    internet: "Средний",
    nomadVisa: "Да",
    banking: "Развивающаяся",
  },
  грузия: {
    cost: "$600",
    climate: "Умеренно-континентальный",
    safety: "Средняя",
    healthcare: "Базовая",
    internet: "Хороший",
    nomadVisa: "Да",
    banking: "Развивающаяся",
  },
  мексика: {
    cost: "$900",
    climate: "Тропический/сухой",
    safety: "Средняя",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Да",
    banking: "Развитая",
  },
  португалия: {
    cost: "$1200",
    climate: "Средиземноморский",
    safety: "Высокая",
    healthcare: "Хорошая",
    internet: "Отличный",
    nomadVisa: "Да",
    banking: "Развитая",
  },
  таиланд: {
    cost: "$800",
    climate: "Тропический",
    safety: "Средняя",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Пока нет",
    banking: "Средняя",
  },
  турция: {
    cost: "$700",
    climate: "Разнообразный",
    safety: "Средняя",
    healthcare: "Средняя",
    internet: "Хороший",
    nomadVisa: "Нет",
    banking: "Средняя",
  },
};
