import type { Country } from '@/entities/country/model/types';

export const manualCountriesData: Partial<Record<string, Partial<Country>>> = {
  armenia: {
    name: { ru: 'Армения', en: 'Armenia' },
    language: 'Армянский, Русский',
    visa: 'Без визы до 180 дней',
    costOfLiving: 850,
    safety: 'medium',
    internetSpeed: 52,
    climate: 'continental',
    salary: 720,
    rent: 350,
    groceries: 250,
    immigrationDifficulty: 'easy',
    taxes: 20,
    freelanceFriendly: true,
    englishLevel: 'low',
    healthcare: 'basic',
    transport: 25,
    nomadVisa: false,
    banking: 'medium',
    russianCommunity: true,
  },
  serbia: {
    name: { ru: 'Сербия', en: 'Serbia' },
    language: 'Сербский',
    visa: 'Без визы до 30 дней',
    costOfLiving: 950,
    safety: 'medium',
    internetSpeed: 65,
    climate: 'continental',
    salary: 1050,
    rent: 400,
    groceries: 280,
    immigrationDifficulty: 'medium',
    taxes: 15,
    freelanceFriendly: true,
    englishLevel: 'medium',
    healthcare: 'medium',
    transport: 40,
    nomadVisa: true,
    banking: 'medium',
    russianCommunity: true,
  },
  philippines: {
    name: { ru: 'Филиппины', en: 'Philippines' },
    language: 'Филиппинский, Английский',
    visa: 'Виза по прибытии 30 дней',
    costOfLiving: 750,
    safety: 'low',
    internetSpeed: 30,
    climate: 'tropical',
    salary: 450,
    rent: 300,
    groceries: 220,
    immigrationDifficulty: 'medium',
    taxes: 25,
    freelanceFriendly: false,
    englishLevel: 'high',
    healthcare: 'basic',
    transport: 25,
    nomadVisa: false,
    banking: 'weak',
    russianCommunity: false,
  },
  vietnam: {
    name: { ru: 'Вьетнам', en: 'Vietnam' },
    language: 'Вьетнамский',
    visa: 'E-visa 90 дней',
    costOfLiving: 800,
    safety: 'medium',
    internetSpeed: 55,
    climate: 'tropical',
    salary: 520,
    rent: 350,
    groceries: 200,
    immigrationDifficulty: 'medium',
    taxes: 20,
    freelanceFriendly: true,
    englishLevel: 'low',
    healthcare: 'medium',
    transport: 20,
    nomadVisa: true,
    banking: 'medium',
    russianCommunity: false,
  },
  albania: {
    name: { ru: 'Албания', en: 'Albania' },
    language: 'Албанский',
    visa: 'Без визы до 1 года',
    costOfLiving: 850,
    safety: 'high',
    internetSpeed: 45,
    climate: 'subtropical',
    salary: 750,
    rent: 350,
    groceries: 220,
    immigrationDifficulty: 'easy',
    taxes: 15,
    freelanceFriendly: true,
    englishLevel: 'medium',
    healthcare: 'medium',
    transport: 25,
    nomadVisa: true,
    banking: 'weak',
    russianCommunity: true,
  },
  georgia: {
    name: { ru: 'Грузия', en: 'Georgia' },
    language: 'Грузинский',
    visa: 'Без визы до 1 года',
    costOfLiving: 900,
    safety: 'medium',
    internetSpeed: 48,
    climate: 'subtropical',
    salary: 650,
    rent: 400,
    groceries: 250,
    immigrationDifficulty: 'easy',
    taxes: 20,
    freelanceFriendly: true,
    englishLevel: 'low',
    healthcare: 'basic',
    transport: 20,
    nomadVisa: true,
    banking: 'weak',
    russianCommunity: true,
  },
  mexico: {
    name: { ru: 'Мексика', en: 'Mexico' },
    language: 'Испанский',
    visa: 'Виза до 180 дней',
    costOfLiving: 1100,
    safety: 'medium',
    internetSpeed: 50,
    climate: 'tropical',
    salary: 850,
    rent: 500,
    groceries: 300,
    immigrationDifficulty: 'medium',
    taxes: 30,
    freelanceFriendly: true,
    englishLevel: 'low',
    healthcare: 'medium',
    transport: 40,
    nomadVisa: true,
    banking: 'strong',
    russianCommunity: false,
  },
  portugal: {
    name: { ru: 'Португалия', en: 'Portugal' },
    language: 'Португальский',
    visa: 'Шенген, D7 виза',
    costOfLiving: 1500,
    safety: 'high',
    internetSpeed: 90,
    climate: 'oceanic',
    salary: 1350,
    rent: 900,
    groceries: 400,
    immigrationDifficulty: 'hard',
    taxes: 28,
    freelanceFriendly: true,
    englishLevel: 'medium',
    healthcare: 'advanced',
    transport: 45,
    nomadVisa: true,
    banking: 'strong',
    russianCommunity: false,
  },
  thailand: {
    name: { ru: 'Таиланд', en: 'Thailand' },
    language: 'Тайский',
    visa: 'Без визы 60 дней',
    costOfLiving: 950,
    safety: 'medium',
    internetSpeed: 65,
    climate: 'tropical',
    salary: 750,
    rent: 400,
    groceries: 250,
    immigrationDifficulty: 'medium',
    taxes: 35,
    freelanceFriendly: false,
    englishLevel: 'low',
    healthcare: 'advanced',
    transport: 25,
    nomadVisa: true,
    banking: 'strong',
    russianCommunity: false,
  },
  turkiye: {
    name: { ru: 'Турция', en: 'Turkey' },
    language: 'Турецкий',
    visa: 'Без визы 60 дней',
    costOfLiving: 900,
    safety: 'medium',
    internetSpeed: 55,
    climate: 'continental',
    salary: 950,
    rent: 350,
    groceries: 250,
    immigrationDifficulty: 'medium',
    taxes: 22,
    freelanceFriendly: true,
    englishLevel: 'low',
    healthcare: 'medium',
    transport: 20,
    nomadVisa: true,
    banking: 'strong',
    russianCommunity: true,
  },
  montenegro: {
    name: { ru: 'Черногория', en: 'Montenegro' },
    language: 'Черногорский',
    visa: 'Без визы до 90 дней',
    costOfLiving: 1100,
    safety: 'high',
    internetSpeed: 50,
    climate: 'oceanic',
    salary: 900,
    rent: 500,
    groceries: 300,
    immigrationDifficulty: 'medium',
    taxes: 15,
    freelanceFriendly: true,
    englishLevel: 'medium',
    healthcare: 'medium',
    transport: 30,
    nomadVisa: true,
    banking: 'weak',
    russianCommunity: true,
  },
  indonesia: {
    name: { ru: 'Индонезия (Бали)', en: 'Indonesia (Bali)' },
    language: 'Индонезийский',
    visa: 'Виза по прибытии 30 дней',
    costOfLiving: 1000,
    safety: 'medium',
    internetSpeed: 35,
    climate: 'tropical',
    salary: 450,
    rent: 500,
    groceries: 250,
    immigrationDifficulty: 'medium',
    taxes: 25,
    freelanceFriendly: true,
    englishLevel: 'medium',
    healthcare: 'medium',
    transport: 30,
    nomadVisa: true,
    banking: 'medium',
    russianCommunity: false,
  },
  spain: {
    name: { ru: 'Испания', en: 'Spain' },
    language: 'Испанский',
    visa: 'Шенген, Digital Nomad виза',
    costOfLiving: 1600,
    safety: 'high',
    internetSpeed: 100,
    climate: 'oceanic',
    salary: 2100,
    rent: 900,
    groceries: 400,
    immigrationDifficulty: 'hard',
    taxes: 24,
    freelanceFriendly: true,
    englishLevel: 'medium',
    healthcare: 'advanced',
    transport: 50,
    nomadVisa: true,
    banking: 'strong',
    russianCommunity: false,
  },
  malaysia: {
    name: { ru: 'Малайзия', en: 'Malaysia' },
    language: 'Малайский, Английский',
    visa: 'Без визы 90 дней',
    costOfLiving: 900,
    safety: 'medium',
    internetSpeed: 60,
    climate: 'tropical',
    salary: 900,
    rent: 400,
    groceries: 200,
    immigrationDifficulty: 'medium',
    taxes: 26,
    freelanceFriendly: true,
    englishLevel: 'high',
    healthcare: 'advanced',
    transport: 25,
    nomadVisa: true,
    banking: 'strong',
    russianCommunity: false,
  },
  uae: {
    name: { ru: 'ОАЭ', en: 'UAE' },
    language: 'Арабский, Английский',
    visa: 'Виза по прибытии 30 дней',
    costOfLiving: 2500,
    safety: 'high',
    internetSpeed: 150,
    climate: 'arid',
    salary: 3500,
    rent: 1500,
    groceries: 500,
    immigrationDifficulty: 'medium',
    taxes: 0,
    freelanceFriendly: true,
    englishLevel: 'high',
    healthcare: 'advanced',
    transport: 80,
    nomadVisa: true,
    banking: 'strong',
    russianCommunity: true,
  },
  cyprus: {
    name: { ru: 'Кипр', en: 'Cyprus' },
    language: 'Греческий, Турецкий',
    visa: 'Про-виза онлайн',
    costOfLiving: 1400,
    safety: 'high',
    internetSpeed: 70,
    climate: 'oceanic',
    salary: 1500,
    rent: 700,
    groceries: 350,
    immigrationDifficulty: 'medium',
    taxes: 12,
    freelanceFriendly: true,
    englishLevel: 'high',
    healthcare: 'advanced',
    transport: 40,
    nomadVisa: true,
    banking: 'strong',
    russianCommunity: true,
  },
};
